#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# work around to fix zm API not working
SRC=/usr/local/src
SHA_SUM="c3976f1478c681b0bbc132ec3a3e82c3984eeed5"
URL="https://github.com/FriendsOfCake/crud/archive/${SHA_SUM}.tar.gz"

dl $URL $SRC
mv ${SRC}/${SHA_SUM}.tar.gz ${SRC}/crud.tar.gz
