#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

dl https://zmrepo.zoneminder.com/debian/archive-keyring.gpg /usr/share/keyrings
cat /usr/share/keyrings/archive-keyring.gpg | gpg --dearmor > /usr/share/keyrings/zoneminder.gpg
rm /usr/share/keyrings/archive-keyring.gpg
