#!/bin/sh -ex

install() {
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# remove unrequired webcp icons (all except those named)
cd /var/www/images
find . -type f ! -name "adminer.png" ! -name "shell.png" ! -name "tab.png" ! -name "webmin.png" -delete

a2enmod cgi
a2enmod rewrite
a2dissite 000-default
a2ensite zoneminder
a2ensite tkl-webcp-zm
service apache2 start

MYSQL_BATCH="mysql --batch"

# Temporarily replace systemctl with our wrapper
# since the zoneminder package uses a hardcoded path
# to call it
mv /usr/bin/systemctl /usr/bin/systemctl.orig
ln -s /usr/local/bin/systemctl /usr/bin

#Install Zoneminder (repo and pin in overlay)
install zoneminder
a2enconf zoneminder
rm /usr/bin/systemctl
mv /usr/bin/systemctl.orig /usr/bin/systemctl

service apache2 stop

service mysql start
cat /usr/share/zoneminder/db/zm_create.sql | $MYSQL_BATCH

# zmpass is changed at firstboot non-interactively (Secure At First Boot)
$MYSQL_BATCH -e "grant all on zm.* to 'zmuser'@localhost identified by 'zmpass';"
# Enable authentication (i.e. force users to log in to ZM)
$MYSQL_BATCH -e "update zm.Config set Value=1 where Name='ZM_OPT_USE_AUTH';"

service mysql stop

#Permissions Editing
chmod 740 /etc/zm/zm.conf
chown root:www-data /etc/zm/zm.conf

#Enable Zoneminder
/usr/bin/systemctl enable zoneminder.service

#Add www-data to video
adduser www-data video
