#!/bin/sh -ex

SRC=/usr/local/src

#ensure datafiles (eg. innodb) are created
/etc/init.d/mysql start
/etc/init.d/mysql stop

# remove unrequired webcp icons (all except those named)
cd /var/www/images
find . -type f ! -name "adminer.png" ! -name "shell.png" ! -name "tab.png" ! -name "webmin.png" -delete

#Install Zoneminder
dpkg -i $SRC/zone*.deb 

#Start MySQL
/etc/init.d/mysql start

#Execute Zoneminder Install Script
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_BATCH < /usr/share/zoneminder/db/zm_create.sql
#zmpass is changed at firstboot non-interactively (Secure At First Boot)
$MYSQL_BATCH -e "grant all on zm.* to 'zmuser'@localhost identified by 'zmpass';"
$MYSQL_ADMIN reload

#Permissions Editing
chmod 740 /etc/zm/zm.conf
chown root:www-data /etc/zm/zm.conf

#Enable Zoneminder
systemctl enable zoneminder.service

#Add www-data to video
adduser www-data video

#Start zoneminder
systemctl start zoneminder.service

#Check Status
systemctl status zoneminder.service

#Enable apache mods
a2enmod cgi
a2enmod rewrite
a2enconf zoneminder

#Add debian backports for use when administering appliance
echo 'deb http://http.debian.net/debian jessie-backports main' >> /etc/apt/sources.list

#Update
apt-get -y update

#Change permissions in zoneminder folder
chown -R www-data:www-data /usr/share/zoneminder/

#Add lines to zoneminder.conf
echo "<Directory /usr/share/zoneminder/www/api>
    AllowOverride All
</Directory>" >> /etc/apache2/conf-enabled/zoneminder.conf 
