#!/bin/bash -e
# regenerate zoneminer secrets and zmuser mysql password

. /etc/default/inithooks

CONF=/etc/zm/zm.conf

USER=zmuser
PASSWORD=$(mcookie)
SECRET=$(mcookie)$(mcookie)

sed -i "/ZM_DB_PASS/ s|=.*|=$PASSWORD|"

$INITHOOKS_PATH/bin/mysqlconf.py --user="$USER" --pass="$PASSWORD"

mysql -u $USER -p$PASSWORD -D zm -e "UPDATE Config SET Value=\"$SECRET\" WHERE Id=6 and Name='ZM_AUTH_HASH_SECRET';"

