#!/bin/bash -e
# regenerate zoneminer secrets and zmuser mysql password

. /etc/default/inithooks

CONF=/etc/zm/zm.conf

USER=zmuser
PASSWORD=$(mcookie)
SECRET=$(mcookie)$(mcookie)

sed -i "/ZM_DB_PASS/ s|=.*|=$PASSWORD|" "$CONF"

mysql --batch <<EOF
ALTER USER '$USER'@'localhost' IDENTIFIED BY '$PASSWORD';
UPDATE zm.Config SET Value='$SECRET' WHERE Name='ZM_AUTH_HASH_SECRET';
EOF
