#!/bin/bash -e
# set timezone in php.ini

. /etc/default/inithooks

TIMEZONE=$(timedatectl show --property=Timezone --value)
[ -n "$TIMEZONE" ] || TIMEZONE=Etc/UTC

[ -e "$INITHOOKS_CONF" ] && . "$INITHOOKS_CONF"
$INITHOOKS_PATH/bin/timezone.py --tz="$TIMEZONE"
