#!/bin/bash -e
# set zmuser database password non-interactive

. /etc/default/inithooks

TIMEZONE=$(curl http://ip-api.com/line/?fields=timezone)
if [ -z "$TIMEZONE" ]
then 
   TIMEZONE="Etc/UTC"
fi

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/timezone.py --tz="$TIMEZONE"
