#!/bin/bash -e
# set timezone in php.ini

. /etc/default/inithooks

TIMEZONE=$(curl --silent --show-error http://ip-api.com/line/?fields=timezone)
if [ -z "$TIMEZONE" ]
then 
   TIMEZONE="Etc/UTC"
fi

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/timezone.py --tz="$TIMEZONE"
